language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install ansible
before_script:
  - ansible --version
  - printf '[defaults]\nroles_path=../localsetup/' >ansible.cfg
script:
  - ansible-playbook ./localsetup/tests/test.yml -i ./localsetup/tests/inventory --syntax-check
