language: python
sudo: true
python:
  - "2.7"
install:
  - pip install ansible
before_script:
  - ansible --version
script:
  - ansible-playbook ./localsetup/roles/test/travis-ci.yml -i ./localsetup/roles/test/hosts --syntax-check
