language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install ansible
before_script:
  - ansible --version
script:
  - ansible-playbook ./localsetup/playbook.yml -i ./localsetup/inventory --syntax-check
  - ansible-playbook ./localsetup/docker-playbook.yml -i ./localsetup/inventory --syntax-check
