language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
      - python-pip
install:
  - pip install -r ./requirements.txt
before_script:
  - ansible --version
script:
  - ansible-lint *playbook.yml
