language: python
sudo: true
python:
  - "2.7"
install:
  - python --version
  - pip --version
  - sudo python --version
  - sudo pip --version
  - pip install ansible
  - sudo apt-get install python-apt
  - python -m pip install python-apt
before_script:
  - ansible --version
  - bash -x ./localsetup/roles/test/before_script.sh
script:
  - ansible-playbook --syntax-check ./localsetup/roles/test/travis-ci.yml -i ./localsetup/roles/test/hosts
  - ansible-playbook ./localsetup/roles/test/travis-ci.yml -i ./localsetup/roles/test/hosts
  - bash -x ./localsetup/roles/test/test.sh
