- name: add slack repository
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ {{ ansible_distribution_release }} main
    state: present
- name: install slack
  apt:
    name: slack
