- name: add slack repository
  apt_repository:
    repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
    state: present
- name: install slack
  apt:
    name: slack
    update_cache: yes
