- name: install git
  apt:
    name: git
    update_cache: yes
- name: git setting user name
  git_config:
    name: user.name
    scope: global
    value: 223n
- name: git setting user email
  git_config:
    name: user.email
    scope: global
    value: '223n@223n.tech'
- name: git setting editor
  git_config:
    name: core.editor
    scope: global
    value: nano
- name: git setting quotepath
  git_config:
    name: core.quotepath
    scope: global
    value: false
- name: git setting color ui
  git_config:
    name: color.ui
    scope: global
    value: true
- name: git setting color diff
  git_config:
    name: color.diff
    scope: global
    value: auto
- name: git setting color status
  git_config:
    name: color.status
    scope: global
    value: auto
- name: git setting color branch
  git_config:
    name: color.branch
    scope: global
    value: auto
